# Generated by Django 4.2.4 on 2023-08-22 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن بدنه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/articles', verbose_name='تصویر')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت')),
                ('published', models.BooleanField(default=True, verbose_name='انتشار')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ('-created',),
            },
        ),
    ]
